alias: 'Shares: Update prices'
trigger:
- platform: time_pattern
  minutes: /5
condition:
- condition: time
  after: 07:59:00
  before: '20:01:00'
  weekday:
  - mon
  - tue
  - wed
  - thu
  - fri
action:
- service: yahoofinance.refresh_symbols
mode: single
