language: python
python:
- "3.7"
before_install:
- mv travis_secrets.yaml secrets.yaml
- mv .travis_ip_authenticated.yaml .ip_authenticated.yaml
- sudo apt-get install -y libudev-dev
install:
- pip3 install homeassistant
script:
- hass -c . --script check_config
