
#
# Travis CI configuration
#
# Simply tests that Home Assistant configuration is valid.
#
# @link https://docs.travis-ci.com/user/tutorial/
# @link https://www.home-assistant.io/docs/ecosystem/backup/backup_github/#step-7-configuration-file-testing
#

# Select the base environment
language: python
python:
  - "3.7"

# Enable Travis caching of Python Packages (per branch)
cache: pip

# Prepare the CI environment to support Home Assistant
before_install:
  - cp travis_secrets.yaml secrets.yaml
  - touch home-assistant_v2.db
  - touch home-assistant.log
  - mkdir config
  - mkdir share
  - HA_VERSION=$(<.HA_VERSION)

  # Add Beautiful Soup (otherwise Travis cannot find its alias bs4)
  - pip3 install beautifulsoup4

  # Fix for missing homeassistant-ptozw 0.1.4 and pydispatcher 2.0.5
  # @link https://community.home-assistant.io/t/travis-ci-build-issues/119482
  - sudo apt-get install --assume-yes libudev-dev

  # Add mising Bluetooth headers
  # @link https://github.com/pybluez/pybluez/issues/236
  - sudo apt-get install --assume-yes libbluetooth-dev
  - pip3 install pybluez==0.22

# Install Home Assistant
install:
  - pip3 install homeassistant==${HA_VERSION}

# Test configuration files
script:
  - hass --script check_config --config . --files
