- id: 1209E804-F447-40E9-A310-98B1EEC00D66
  alias: 'Shares: Update prices'
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: 07:59:00
    before: '20:01:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: yahoofinance.refresh_symbols
  mode: single
- id: 184E5AB9-BC4B-4082-91B8-D8DD0C81D114
  alias: 'Shares: GME'
  trigger:
  - platform: numeric_state
    entity_id: yahoofinance.gme
    below: '200'
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.officemini
      message: The GME shares are below 200$
  mode: single
- id: '1616113487256'
  alias: Water the Plant
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.soil_moisture_level
    below: '65'
  condition:
  - condition: sun
    before: sunset
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.kitchenmini
      message: Your plant need water
  - service: notify.mobile_app_pete_s20
    data:
      message: Please water the plant
      title: Plant
  mode: single
- id: '1616116127975'
  alias: Dishwasher test
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dishwasher_dishwasher_job_state
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.kitchenmini
      message: the dishwasher is now {{states.sensor.dishwasher_dishwasher_job_state.state}}
  mode: single
- id: '1600194112743'
  alias: Restart HA
  description: ''
  trigger:
  - at: 02:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
- id: '1616421976640'
  alias: Temp Office Below outside
  description: ''
  trigger:
  - platform: template
    value_template: "{{ states.sensor.openweathermap_temperature.state < \n     states.sensor.office_temperature_2.state\
      \ }}"
  condition:
  - condition: sun
    before: sunset
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.officemini
      message: The temperature outside is below the temp inside
  mode: single
- id: '1616718704686'
  alias: Notification Test
  description: ''
  trigger:
  - platform: state
    entity_id: person.pierre
    from: Home
    to: Away
  condition: []
  action:
  - service: notify.mobile_app_pete_s20
    data:
      title: HA - Notify
      message: Home -> Away
  mode: single
- id: '1617646087748'
  alias: Rain Alert
  description: ''
  trigger:
  - platform: time
    at: '14:15:00'
  condition:
  - condition: template
    value_template: '{{ ''cloudy'' in state_attr(''weather.my_home'', ''forecast'')[:days]  |
      map(attribute=''condition'') }}  '
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Rain is expected, close the window
  mode: single
  variables:
    days: 4
- id: '1617646293726'
  alias: Rain Alert
  description: ''
  trigger:
  - platform: time
    at: '14:15:00'
  condition:
  - condition: template
    value_template: '{{ ''cloudy'' in state_attr(''weather.maison_2'', ''forecast'')[:days]  |
      map(attribute=''condition'') }}  '
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Rain is expected, close the window
  variables:
    days: 4
  mode: single
- id: '1617649810386'
  alias: Rain Alert Bool Turn On
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: template
    value_template: '{{ states.weather.maison_2.attributes.forecast[1].precipitation_probability
      >= 51 }}'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.rain_tomorrow
  mode: single
- id: '1617650162551'
  alias: Rain Alert Bool Turn Off
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: template
    value_template: '{{ states.weather.maison_2.attributes.forecast[1].precipitation_probability
      <= 50 }}'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.rain_tomorrow
  mode: single
