- id: 1209E804-F447-40E9-A310-98B1EEC00D66
  alias: 'Shares: Update prices'
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: 07:59:00
    before: '20:01:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: yahoofinance.refresh_symbols
  mode: single
- id: 184E5AB9-BC4B-4082-91B8-D8DD0C81D114
  alias: 'Shares: GME'
  trigger:
  - platform: numeric_state
    entity_id: yahoofinance.gme
    below: '200'
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.officemini
      message: The GME shares are below 200$
  mode: single
- id: '1616113487256'
  alias: Water the Plant
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.soil_moisture_level
    below: '50.0'
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.kitchenmini
      message: Your plant need water
  mode: single
- id: '1616116127975'
  alias: Dishwasher test
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dishwasher_dishwasher_job_state
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.kitchenmini
      message: the dishwasher is now {{states.sensor.dishwasher_dishwasher_job_state.state}}
  mode: single
- id: '1600194112743'
  alias: Restart HA
  description: ''
  trigger:
  - at: 02:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
- id: '1616421976640'
  alias: Temp Office Below outside
  description: ''
  trigger:
  - platform: template
    value_template: "{{ states.sensor.openweathermap_temperature.state < \n     states.sensor.office_temperature_2.state\
      \ }}"
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.officemini
      message: The temperature outside is below the temp inside
  mode: single
