- id: dishwasher
  alias: Dishwasher test
  description: ''
  trigger:
  - platform: state
    entity_id: sensor.dishwasher_dishwasher_job_state
  condition:
  - condition: sun
    before: sunset
    after: sunrise
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.kitchenmini
      message: the dishwasher is now {{states.sensor.dishwasher_dishwasher_job_state.state}}
  mode: single
- id: homenotoccupied
  alias: Home not occupied
  trigger:
  - platform: state
    entity_id: device_tracker.julie_s20
    from: home
  - platform: state
    entity_id: device_tracker.pete_s20
    from: home
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.home_occupied
  initial_state: true
  mode: single
- id: homeoccupied
  alias: Home occupied
  trigger:
  - platform: state
    entity_id: device_tracker.julie_s20,device_tracker.pete_s20
    to: home
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.home_occupied
  initial_state: true
  mode: single
- id: housebedtime
  alias: House Bedtime Julie
  trigger:
  - platform: state
    entity_id:
    - input_boolean.julie_in_bed
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.pete_in_bed
    state: 'on'
  - condition: time
    after: '21:30'
    before: '5:00'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.bedtime
  - service: notify.mobile_app_pete_s20
    data:
      message: Bedtime!
  initial_state: true
  mode: single
- id: tempofficebelowoutside
  alias: Temp Office Below outside
  description: ''
  trigger:
  - platform: template
    value_template: "{{ states.sensor.environment_canada_temperature.state < \n  \
      \   states.sensor.office_temperature.state }}"
  condition:
  - condition: sun
    before: sunset
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.officemini
      message: The temperature outside is below the temp inside
  mode: single
- id: waterplants
  alias: Water the Plant
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.plante_max_moisture_level
    below: '25'
  condition:
  - condition: sun
    before: sunset
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.kitchenmini
      message: Your plant need water
  - service: notify.mobile_app_pete_s20
    data:
      message: Please water the plant
      title: Plant
  mode: single
- id: nintendowishlist
  alias: Nintendo WIshlist
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.nintendo_wishlist_final_fantasy_viii_remastered
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: THe game is on sale Nintendo
  mode: single
- id: sharesgme
  alias: 'Shares: GME'
  trigger:
  - platform: numeric_state
    entity_id: yahoofinance.gme
    below: '200'
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.officemini
      message: The GME shares are below 200$
  mode: single
- id: updatestock
  alias: 'Shares: Update prices'
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: 07:59:00
    before: '20:01:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: yahoofinance.refresh_symbols
  mode: single
- id: julieinbed
  alias: Julie in bed
  trigger:
  - platform: state
    entity_id: binary_sensor.julie_s20_en_charge
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.julie_in_bed
      state: 'off'
    - condition: state
      entity_id: device_tracker.julie_s20_ping
      state: home
    - condition: time
      after: '21:00:00'
      before: 05:00:00
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.julie_in_bed
  initial_state: true
- id: julieisup
  alias: Julie is Up
  trigger:
  - platform: state
    entity_id: binary_sensor.julie_s20_en_charge
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.julie_s20
      state: home
    - condition: state
      entity_id: input_boolean.julie_in_bed
      state: 'on'
    - condition: time
      after: 05:00:00
      before: '21:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.bedtime
      - input_boolean.julie_in_bed
  initial_state: true
  mode: single
- id: peteinbed
  alias: Pete in bed
  trigger:
  - platform: state
    entity_id: binary_sensor.pete_s20_is_charging
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.pete_in_bed
      state: 'off'
    - condition: state
      entity_id: device_tracker.pete_s20
      state: home
    - condition: time
      after: '21:00:00'
      before: 05:00:00
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.pete_in_bed
  initial_state: true
  mode: single
- id: peteisup
  alias: Pete is Up
  trigger:
  - platform: state
    entity_id: binary_sensor.pete_s20_is_charging
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.pete_is_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.pete_in_bed
      state: 'on'
    - condition: time
      after: 05:00:00
      before: '21:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.bedtime
      - input_boolean.pete_in_bed
  initial_state: true
  mode: single
- id: peteishome
  alias: Pete Is Home
  description: ''
  mode: single
  trigger:
  - platform: state
    entity_id: device_tracker.pete_s20_ping
    to: home
  condition: []
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.pete_is_home
- id: hareloaded
  alias: HA automations reloaded
  initial_state: true
  trigger:
  - platform: event
    event_type: automation_reloaded
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Automations on Server have been reloaded at {{ as_timestamp(now())|timestamp_local
        }} local
      title: HA automations reloaded
- id: harestart
  alias: Ha restart
  description: ''
  trigger:
  - at: 02:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
- id: start
  alias: HA started
  initial_state: true
  trigger:
    platform: homeassistant
    event: start
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Home Assistant {{ states('sensor.latest_version') }} has started on
        Server ({{ as_timestamp(utcnow())|timestamp_utc }})
- id: haupdate
  alias: HA Update Available Notifications
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: update available
  initial_state: true
  mode: single
- id: rainalertoff
  alias: Rain Alert Bool Turn Off
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: template
    value_template: '{{ states.weather.quebec.attributes.forecast[1].precipitation_probability
      <= 50 }}'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id: input_boolean.rain_tomorrow
  mode: single
- id: rainaleron
  alias: Rain Alert Bool Turn On
  description: ''
  trigger:
  - platform: time
    at: '16:00:00'
  condition:
  - condition: template
    value_template: '{{ states.weather.quebec.attributes.forecast[1].precipitation_probability
      >= 51 }}'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.rain_tomorrow
  mode: single
- id: rainalert
  alias: Rain Alert
  description: ''
  trigger:
  - platform: time
    at: '14:15:00'
  condition:
  - condition: template
    value_template: '{{ ''cloudy'' in state_attr(''weather.maison_2'', ''forecast'')[:days]  |
      map(attribute=''condition'') }}  '
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Rain is expected, close the window
  variables:
    days: 4
  mode: single
- id: '1619007437837'
  alias: House Bedtime Pete
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.pete_in_bed
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.julie_in_bed
    state: 'on'
  - condition: time
    after: '21:30'
    before: '5:00'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.bedtime
  - service: notify.mobile_app_pete_s20
    data:
      message: Bedtime!
  mode: single
  initial_state: true
