- id: homenotoccupied
  alias: Home - Not occupied
  trigger:
  - platform: state
    entity_id:
    - device_tracker.julie_s20
    - device_tracker.pete_s20
    from: home
  action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.home_occupied
  - service: light.turn_off
    data:
      transition: 37
    target:
      entity_id: light.all_lights
  initial_state: true
  mode: single
- id: homeoccupied
  alias: Home - Occupied
  trigger:
  - platform: state
    entity_id: device_tracker.julie_s20,device_tracker.pete_s20
    to: home
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.home_occupied
  initial_state: true
  mode: single
- id: housebedtime
  alias: Home - Bedtime Julie
  trigger:
  - platform: state
    entity_id:
    - input_boolean.julie_in_bed
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.pete_in_bed
    state: 'on'
  - condition: time
    after: '21:30'
    before: '5:00'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.bedtime
  - service: notify.mobile_app_pete_s20
    data:
      message: Bedtime!
  initial_state: true
  mode: single
- id: tempofficebelowoutside
  alias: Climate - Temp Office Below outside
  description: ''
  trigger:
  - platform: template
    value_template: "{{ states.sensor.environment_canada_temperature.state < \n  \
      \   states.sensor.office_temperature.state }}"
  condition:
  - condition: sun
    before: sunset
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.officemini
      message: The temperature outside is below the temp inside
  mode: single
- id: waterplants
  alias: Home - Water the Plant
  description: ''
  trigger:
  - platform: numeric_state
    entity_id: sensor.plante_max_moisture_level
    below: '25'
  condition:
  - condition: sun
    before: sunset
  action:
  - service: tts.google_translate_say
    data:
      message: Your plant need water
      entity_id: media_player.officemini
  - service: notify.mobile_app_pete_s20
    data:
      message: Please water the plant
      title: Plant
  - service: light.turn_on
    target:
      entity_id: light.office_ceiling_1
    data:
      color_name: red
      brightness_pct: 97
  mode: single
- id: nintendowishlist
  alias: Device - Nintendo Wishlist
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.nintendo_wishlist_final_fantasy_viii_remastered
    to: 'on'
  condition: []
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: THe game is on sale Nintendo
  mode: single
- id: updatestock
  alias: Shares - Update prices
  trigger:
  - platform: time_pattern
    minutes: /5
  condition:
  - condition: time
    after: 07:59:00
    before: '20:01:00'
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: yahoofinance.refresh_symbols
  mode: single
- id: julieinbed
  alias: Home - Julie in bed
  trigger:
  - platform: state
    entity_id: binary_sensor.julie_s20_en_charge
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.julie_in_bed
      state: 'off'
    - condition: state
      entity_id: device_tracker.julie_s20
      state: home
    - condition: time
      after: '21:00:00'
      before: 05:00:00
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.julie_in_bed
  initial_state: true
  mode: single
- id: julieisup
  alias: Home - Julie is Up
  trigger:
  - platform: state
    entity_id: binary_sensor.julie_s20_en_charge
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: device_tracker.julie_s20
      state: home
    - condition: state
      entity_id: input_boolean.julie_in_bed
      state: 'on'
    - condition: time
      after: 05:00:00
      before: '21:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.bedtime
      - input_boolean.julie_in_bed
  initial_state: true
  mode: single
- id: peteinbed
  alias: Home - Pete in bed
  trigger:
  - platform: state
    entity_id: binary_sensor.pete_s20_is_charging
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.pete_in_bed
      state: 'off'
    - condition: state
      entity_id: device_tracker.pete_s20
      state: home
    - condition: time
      after: '21:00:00'
      before: 05:00:00
  action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.pete_in_bed
  initial_state: true
  mode: single
- id: peteisup
  alias: Home - Pete is Up
  trigger:
  - platform: state
    entity_id: binary_sensor.pete_s20_is_charging
    to: 'off'
  condition:
  - condition: and
    conditions:
    - condition: state
      entity_id: input_boolean.pete_is_home
      state: 'on'
    - condition: state
      entity_id: input_boolean.pete_in_bed
      state: 'on'
    - condition: time
      after: 05:00:00
      before: '21:00:00'
  action:
  - service: input_boolean.turn_off
    target:
      entity_id:
      - input_boolean.bedtime
      - input_boolean.pete_in_bed
  initial_state: true
  mode: single
- id: hareloaded
  alias: HA - Automations reloaded
  trigger:
  - platform: event
    event_type: automation_reloaded
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Automations on Server have been reloaded at {{ as_timestamp(now())|timestamp_local
        }} local
      title: HA automations reloaded
  initial_state: true
  mode: single
- id: harestart
  alias: HA - Restart
  description: ''
  trigger:
  - at: 02:00:00
    platform: time
  condition:
  - condition: time
    weekday:
    - sun
  action:
  - data: {}
    service: homeassistant.restart
  mode: single
- id: start
  alias: HA - Started
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Home Assistant {{ states('sensor.current_version') }} has started on
        Server ({{ as_timestamp(utcnow())|timestamp_utc }})
  initial_state: true
  mode: single
- id: haupdate
  alias: HA - Update Available Notifications
  trigger:
  - platform: state
    entity_id: updater.updater
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: update available
  initial_state: true
  mode: single
- id: rainaleron
  alias: Rain Alert Turn On
  description: ''
  trigger:
  - platform: state
    to: 'on'
    entity_id: binary_sensor.rain_alert
  condition: []
  action:
  - service: notify.mobile_app_pete_s20
    data:
      message: Rain is expected, close the window
      title: Rain
  mode: single
  variables:
    days: 4
- id: '1619007437837'
  alias: Home - Bedtime Pete
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.pete_in_bed
    to: 'on'
  condition:
  - condition: state
    entity_id: input_boolean.julie_in_bed
    state: 'on'
  - condition: time
    after: '21:30'
    before: '5:00'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.bedtime
  - service: notify.mobile_app_pete_s20
    data:
      message: Bedtime!
  mode: single
  initial_state: true
- id: '1619623777038'
  alias: HA - PushGit
  description: ''
  trigger:
  - platform: time
    at: 02:51:00
  condition: []
  action:
  - service: shell_command.push
  mode: single
- id: '1619632563004'
  alias: Network - Down
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wan
    to: 'off'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: Internet Down
      title: Wan
      notification_id: '1'
  mode: single
- id: '1619632671274'
  alias: Network - Up
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.wan
    to: 'on'
    for:
      hours: 0
      minutes: 1
      seconds: 0
  condition: []
  action:
  - service: persistent_notification.create
    data:
      message: Internet Up
      title: Wan
      notification_id: '1'
  mode: single
- id: '1619659073387'
  alias: HA - Set HA theme
  description: Change theme based on day or night
  trigger:
  - platform: homeassistant
    event: start
  - platform: state
    entity_id: sun.sun
    to: above_horizon
  - platform: state
    entity_id: sun.sun
    to: below_horizon
  - platform: state
    entity_id:
    - input_boolean.maintenance_mode
  action:
  - service: frontend.set_theme
    data_template:
      name: '{% if is_state (''input_boolean.maintenance_mode'' , ''on'') %} dark_orange
        {% elif (is_state (''sun.sun'' , ''below_horizon''))  and is_state (''input_boolean.maintenance_mode''
        , ''off'') %} midnight_blue {% else %} default {% endif %}

        '
  mode: single
- id: '1620512797995'
  alias: 'Lights - Office Light 7AM -> Turn On '
  description: Turn On Office Light 7AM
  trigger:
  - platform: time
    at: 06:55:00
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_on
    target:
      entity_id: light.office_lights
    data:
      brightness_pct: 100
      color_temp: 252
  mode: single
- id: '1620513188057'
  alias: Lights - Turn Off Office Light 10PM
  description: Turn Off Office Light 10PM
  trigger:
  - platform: time
    at: '22:00:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
  action:
  - service: light.turn_off
    target:
      entity_id: light.office_lights
    data:
      transition: 60
  mode: single
- id: '1620513319973'
  alias: Lights - Turn Off Office Light 10PM (Duplicate)
  description: Turn Off Office Light 10PM
  trigger:
  - platform: time
    at: '18:41:00'
  condition:
  - condition: time
    weekday:
    - mon
    - tue
    - wed
    - thu
    - fri
    - sat
    - sun
  action:
  - service: light.turn_off
    target:
      entity_id: light.office_lights
  mode: single
- id: media_stopped_lights_on
  alias: Media - Stopped -> Lights On
  trigger:
  - platform: state
    entity_id: media_player.playstation_4_living
    to: idle
    for: 0:00:05
  - platform: state
    entity_id: media_player.playstation_4_living
    to: paused
    for: 0:00:03
  - platform: state
    entity_id: media_player.playstation_4_living
    to: standby
  condition:
  - condition: time
    after: '18:00:00'
  action:
  - service: light.turn_on
    data:
      transition: 10
      color_temp: 447
      brightness_pct: 40
    target:
      entity_id: light.living_room_lamps
  mode: single
- id: media_started_lights_off
  alias: Media - Started -> Lights Tame
  trigger:
  - platform: state
    entity_id: media_player.playstation_4_living
    to: playing
    for: 0:00:05
  condition:
  - condition: time
    after: '18:45:00'
  action:
  - service: light.turn_on
    data:
      color_temp: 447
      transition: 15
      brightness_pct: 1
    target:
      entity_id: light.living_room_lights
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.watching_tv
  mode: single
- id: media_turn_off_watching_plex_boolean
  alias: Media - Turn Off Watching Plex Boolean
  trigger:
  - platform: state
    entity_id: media_player.playstation_4_living
    to: idle
    for: 0:05:00
  - platform: state
    entity_id: media_player.playstation_4_living
    to: paused
    for: 0:10:00
  - platform: state
    entity_id: media_player.playstation_4_living
    to: unavailable
    for: 0:10:00
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.watching_tv
  mode: single
- id: '1620782893266'
  alias: Home - Bedtime -> Everything OFF
  description: ''
  trigger:
  - platform: state
    entity_id: input_boolean.bedtime
    to: 'on'
  condition: []
  action:
  - service: light.turn_off
    target:
      entity_id: light.all_lights
    data:
      transition: 5
  mode: single
- id: Home_Nearly_Home_Ligths_on
  alias: Home - Nearly Home -> Ligths on
  trigger:
  - platform: zone
    entity_id:
    - device_tracker.pete_s20
    - device_tracker.julie_s20
    zone: zone.home
    event: enter
  condition:
  - condition: state
    entity_id: input_boolean.home_occupied
    state: 'off'
    for: 00:10:00
  - condition: time
    after: '18:00:00'
  action:
  - service: light.turn_on
    target:
      entity_id: light.living_room_lights
    data:
      transition: 15
      color_temp: 420
      brightness_pct: 10
  mode: single
- id: '1620924425457'
  alias: TEST - Home - Nearly Home -> Ligths on
  description: ''
  trigger:
  - platform: zone
    entity_id: device_tracker.julie_s20
    zone: zone.home
    event: enter
  condition: []
  action:
  - service: light.turn_on
    data:
      color_name: darkmagenta
    target:
      entity_id:
      - light.office_ceiling_1
      - light.office_ceiling_2
  mode: single
- id: '1620948261153'
  alias: Media - 18h45 Started -> Lights Tame
  description: ''
  trigger:
  - platform: time
    at: '18:45:00'
  condition:
  - condition: state
    entity_id: media_player.playstation_4_living
    state: playing
  action:
  - service: light.turn_on
    data:
      color_temp: 447
      transition: 15
      brightness_pct: 1
    target:
      entity_id: light.living_room_lights
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.watching_tv
  mode: single
