- platform: ping
  host: 8.8.8.8
  name: WAN
  scan_interval: 60
- platform: ping
  host: 192.168.2.1
  name: Gateway
  scan_interval: 60
- platform: ping
  host: 192.168.2.60
  name: Machine
  scan_interval: 60
- platform: ping
  host: 192.168.2.65
  name: Server
  scan_interval: 60
- platform: ping
  host: 192.168.2.150
  name: Laurel
  scan_interval: 60
- platform: ping
  host: 192.168.2.151
  name: Hardy
  scan_interval: 60
- platform: ping
  host: 192.168.2.105
  name: Dash
  scan_interval: 60
- platform: ping
  host: 192.168.2.120
  name: Living Room ps4
  scan_interval: 60
- platform: ping
  host: 192.168.2.121
  name: Switch
  scan_interval: 60

- platform: workday
  country: CA