# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:


sensor: !include sensors.yaml
shell_command: !include shell_command.yaml
group: !include_dir_named groups/
automation: !include automations.yaml
input_datetime: !include_dir_named input_datetime/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
#input_text: !include_dir_named input_text/
input_boolean: !include_dir_named input_boolean/
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
#device_tracker: !include device_tracker.yaml
nintendo_wishlist: !include nintendo_wishlist.yaml
frontend:
  themes: !include_dir_merge_named themes
# Text to speech
tts:
  - platform: google_translate

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state


recorder:
  purge_keep_days: 14
  db_url: !secret mariadb_conn_string
  exclude:
    entities:
      - sensor.spacex_next_launch_countdown
  #include:
  #domains:
  #- sensor
# Example configuration.yaml entry
proximity:
  home:
    ignored_zones:
      - work
    devices:
      - device_tracker.pete_s20
    tolerance: 50
    unit_of_measurement: km
#history:
#mqtt:
# broker: !secret mqtt_url
#port: !secret mqtt_port
#client_cert: home-assistant
#discovery: true
#discovery: homeassistant



yahoofinance:
  symbols:
    - GME
    - NOW
    - TSLA
    - GOOG
    - BTC-USD
    - MSFT
    - AMZN
  show_trending_icon: true
  scan_interval:
    hours: 24
logger:
    default: info

    # Example configuration.yaml entry
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_token

lovelace:
  # mode: yaml
  # Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
  # Add more dashboards
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true

# https://www.home-assistant.io/integrations/calendar.google/
google:
  client_id: !secret googlecalendar_client_id
  client_secret: !secret googlecalendar_client_secret

  # Example configuration.yaml entry
#spotcast:
#  sp_dc: !secret spotify_spotcast_dc
#  sp_key: !secret spotify_spotcast_key
mqtt:
  discovery: true
  discovery_prefix: homeassistant
  broker: 192.168.2.65
  port: 1883
  client_id: home-assistant-1
  keepalive: 60
  username: !secret mqtt_user
  password: !secret mqtt_pw

# https://www.home-assistant.io/integrations/environment_canada/
weather:
  - platform: environment_canada
    station: QC/s0000620

# https://www.home-assistant.io/integrations/plant/
plant:
  max_plant:
    sensors:
      moisture: sensor.plante_max_moisture_level
      #battery: sensor.my_sensor_battery
      temperature: sensor.office_temperature
      #conductivity: sensor.my_sensor_conductivity
      #brightness: sensor.my_sensor_brightness
    min_moisture: 20

  