# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
#secret: !include secrets.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state

# Example configuration.yaml entry
sensor:
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_use_percent
      - type: network_in
        arg: enp1s0
      - type: network_out
        arg: enp1s0
      - type: processor_use
      - type: processor_temperature
      - type: last_boot
      - type: ipv4_address
        arg: enp1s0

recorder:
  purge_keep_days: 30
  db_url: !secret mariadb_conn_string
  purge_interval: 1
  #include:
  #domains:
  #- sensor
# Example configuration.yaml entry
proximity:
  home:
    ignored_zones:
      - work
    devices:
      - device_tracker.pete_s20
    tolerance: 50
    unit_of_measurement: km
#history:
#mqtt:
# broker: !secret mqtt_url
#port: !secret mqtt_port
#client_cert: home-assistant
#discovery: true
#discovery: homeassistant

binary_sensor:
  - platform: ping
    host: 192.168.2.120
    name: "Switch"
    count: 2
    scan_interval: 600
