# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Text to speech
tts:
  - platform: google_translate

sensor: !include sensors.yaml
shell_command: !include shell_command.yaml
group: !include_dir_named groups/
input_datetime: !include_dir_named input_datetime/
input_number: !include_dir_named input_number/
input_select: !include_dir_named input_select/
#input_text: !include_dir_named input_text/
#input_boolean: !include_dir_named input_boolean/
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
binary_sensor: !include binary_sensor.yaml
device_tracker: !include device_tracker.yaml
#secret: !include secrets.yaml

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret username
  password: !secret influxdb_password
  max_retries: 3
  default_measurement: state


recorder:
  purge_keep_days: 15
  db_url: !secret mariadb_conn_string
  purge_interval: 1
  exclude:
    entities:
      - sensor.spacex_next_launch_countdown
  #include:
  #domains:
  #- sensor
# Example configuration.yaml entry
proximity:
  home:
    ignored_zones:
      - work
    devices:
      - device_tracker.pete_s20
    tolerance: 50
    unit_of_measurement: km
#history:
#mqtt:
# broker: !secret mqtt_url
#port: !secret mqtt_port
#client_cert: home-assistant
#discovery: true
#discovery: homeassistant



yahoofinance:
  symbols:
    - GME
    - NOW
    - TSLA
    - GOOG
    - BTC-USD
    - MSFT
    - AMZN
  show_trending_icon: true
  scan_interval:
    hours: 24
logger:
    default: info

    # Example configuration.yaml entry
spotify:
  client_id: !secret spotify_id
  client_secret: !secret spotify_token

lovelace:
  # mode: yaml
  # Include external resources only add when mode is yaml, otherwise manage in the resources in the lovelace configuration panel.
  # Add more dashboards
  dashboards:
    lovelace-generated: # Needs to contain a hyphen (-)
      mode: yaml
      filename: notexist.yaml
      title: Generated
      icon: mdi:tools
      show_in_sidebar: true
      require_admin: true
