alias: Rain Alert Bool Turn Off
description: ''
trigger:
- platform: time
  at: '16:00:00'
condition:
- condition: template
  value_template: '{{ states.weather.maison_2.attributes.forecast[1].precipitation_probability
    <= 50 }}'
action:
- service: input_boolean.turn_off
  target:
    entity_id: input_boolean.rain_tomorrow
mode: single
