alias: Julie in bed
trigger:
- platform: state
  entity_id: binary_sensor.julie_s20_en_charge
  to: 'on'
condition:
- condition: and
  conditions:
  - condition: state
    entity_id: input_boolean.julie_in_bed
    state: 'off'
  - condition: state
    entity_id: device_tracker.julie_s20_ping
    state: home
  - condition: time
    after: '21:00:00'
    before: 05:00:00
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.julie_in_bed
initial_state: true