initial_state: 'on'
alias: 'Office not occupied'
trigger:
  - platform: state
    entity_id: group.work_laptop
    to: 'not_home'
    for: '00:02:00'
  - platform: state
    entity_id: binary_sensor.office_motion_konke_occupancy
    to: 'off'
    for: '00:01:00'
  - platform: state
    entity_id: binary_sensor.office_door_contact
    to: 'on'
condition:
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'on'
  - condition: state
    entity_id: group.work_laptop
    state: 'not_home'
    for: '00:02:00'
  - condition: state
    entity_id: binary_sensor.office_motion_konke_occupancy
    state: 'off'
    for: '00:01:00'
  - condition: or
    conditions:
    # The door is either open, or if closed not been closed for more than 5 minutes
    - condition: state
      entity_id: binary_sensor.office_door_contact
      state: 'on'
    - condition: not
      conditions:
      - condition: state
        entity_id: binary_sensor.office_door_contact
        state: 'off'
        for: '00:05:00'
action:
  - service: input_boolean.turn_off
    entity_id: 
      - input_boolean.office_occupied
      - input_boolean.stream_front_camera_motion
  - service: switch.turn_off
    entity_id: switch.adaptive_lighting_sleep_mode_office
  - service: input_boolean.turn_on
    entity_id: input_boolean.lighting_living_room
