initial_state: 'on'
alias: 'Office motion'
trigger:
  - platform: state
    entity_id: binary_sensor.office_motion_konke_occupancy
    to: 'on'
  - platform: state
    entity_id: binary_sensor.office_door_contact
    to: 'on'
condition:
  - condition: template
    value_template: "{{ states('input_select.office') not in ('Dim','Wake','On') }}"
  - condition: state
    entity_id: input_boolean.office_occupied
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.pi3_office_multi_luminance
    below: 2
action:
  - service: notify.logfile
    data:
      message: >
        Office Motion triggered at {{ now() }} by {{ trigger.entity_id }}, was {{ trigger.from_state.state }} is {{ trigger.to_state.state }}
          Light level is {{ states('sensor.pi3_office_multi_luminance') }}
  - service: input_select.select_option
    data:
      entity_id: input_select.office
      option: 'Motion'
