alias: 'person3 coming home'
initial_state: 'on'
trigger:
  - platform: numeric_state
    entity_id: proximity.person3_home
    below: 550
  - platform: numeric_state
    entity_id: sensor.person3s_time_to_home_by_foot
    below: 10
condition:
  - condition: state
    entity_id: input_boolean.person3_home
    state: 'off'
  - condition: template
    value_template: '{{ states.proximity.person3_home.attributes.dir_of_travel == "towards"  }}'
  - condition: state
    entity_id: input_select.person2_status_dropdown
    state: 'Home'
  - condition: numeric_state
    entity_id: proximity.person3_home
    below: 550
  - condition: numeric_state
    entity_id: sensor.person3s_time_to_home_by_foot
    below: 10
action:
  - service: notify.logfile
    data:
      message: "SENDME person3's nearly home, and will be home in {{ states('sensor.person3s_time_to_home_by_foot') }} {{ state_attr('sensor.person3s_time_to_home_by_foot','unit_of_measurement') }}"
  - delay: '00:05:00'
