alias: "Not work day for Pete"
initial_state: "on"
trigger:
  - platform: state
    entity_id: calendar.Pete_holiday
    to: "on"
  - platform: homeassistant
    event: start
  - platform: time
    at: "01:00:00"
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: calendar.Pete_holiday
      state: "on"
    - condition: time
      weekday:
        - sat
        - sun
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.notify_Pete_work
