alias: "Pete Up"
initial_state: "on"
trigger:
  # Something gets unplugged
  - platform: state
    entity_id: input_boolean.Pete_phone_charging
    to: "off"
  - platform: state
    entity_id: input_boolean.Pete_tablet_charging
    to: "off"
condition:
  - condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.Pete_home
        state: "on"
      - condition: state
        entity_id: input_boolean.Pete_in_bed
        state: "on"
      - condition: time
        after: "05:00:00"
        before: "21:00:00"
action:
  - service: input_boolean.turn_off
    entity_id:
      - input_boolean.Pete_in_bed
      - input_boolean.Pete_alarm_sounded
  - service: switch.turn_off
    entity_id: switch.adaptive_lighting_sleep_mode_second_bedroom
  - service: notify.logfile
    data:
      message: >
        Turned off Pete in bed because the {{ trigger.to_state.name }} was {{ trigger.to_state.state }} at {{ now() }}
