initial_state: "on"
alias: "Pete tablet home"
trigger:
  - platform: state
    entity_id:
      - group.person_Pete_tablet
    to: "home"
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.Pete_tablet_home
    state: "off"
  - condition: state
    entity_id: group.person_Pete_tablet
    state: "home"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.Pete_tablet_home
