alias: 'person1 awake'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.person1_in_bed
    to: 'off'
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.person1_is_awake
  - service: input_boolean.turn_off
    entity_id: input_boolean.person1_alarm_sounded
  - service: media_player.turn_off
    entity_id:
    - media_player.cast_second_bedroom_speaker
    - media_player.person1
  - service: script.turn_on
    entity_id: script.person1_travel_sensor
