initial_state: "on"
alias: "Pete changing zones"
trigger:
  # Been away for a few minutes
  - platform: state
    entity_id: device_tracker.Pete_mobile
    to: "not_home"
    for: "00:05:00"
  # Arrived in a zone
  - platform: state
    entity_id: device_tracker.Pete_mobile
    from: "not_home"
condition:
  # Been at least 5 minutes
  - condition: template
    value_template: "{{ (now() - state_attr('script.Pete_travel_time','last_triggered')).seconds > 300 }}"
action:
  - service: notify.logfile
    data:
      message: "Updating travel time for Pete due to entering a zone, or leaving one 5 minutes ago"
  - service: script.turn_on
    entity_id: script.Pete_travel_time
