alias: "Pete WiFi status"
initial_state: "on"
trigger:
  - platform: state
    entity_id: sensor.Pete_lenovo_tb_j606f_wifi_connection
action:
  - choose:
      - conditions:
          - condition: template
            value_template: "{{ 'Cogs-n-Gears' in states('sensor.Pete_lenovo_tb_j606f_wifi_connection') }}"
        sequence:
          - service: mqtt.publish
            data:
              topic: location/Pete_wifi
              payload: "home"
              retain: true
    default:
      - service: mqtt.publish
        data:
          topic: location/Pete_wifi
          payload: "not_home"
          retain: true
