initial_state: "off"
alias: "Pete home after work"
trigger:
  platform: state
  entity_id: device_tracker.Pete_mobile
  to: "home"
  for:
    minutes: 10
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.notify_Pete_work
      state: "on"
    - condition: or
      conditions:
        - condition: time
          after: "15:00:00"
          weekday:
            - mon
            - tue
            - wed
            - thu
        - condition: time
          after: "12:00:00"
          weekday:
            - fri
action:
  - service: homeassistant.turn_off
    entity_id: automation.Pete_home_after_work
