alias: "Pete off holiday"
initial_state: "on"
trigger:
  - platform: state
    entity_id: calendar.Pete_holiday
    to: "off"
  - platform: homeassistant
    event: start
  - platform: time
    at: "01:00:00"
condition:
  - condition: state
    entity_id: calendar.Pete_holiday
    state: "off"
action:
  - service: switch.turn_on
    entity_id: switch.radio_Pete
