initial_state: "on"
alias: "Pete location update"
trigger:
  # I've moved
  - platform: state
    entity_id:
      - device_tracker.Pete_mobile
      - input_select.Pete_status_dropdown
      - input_boolean.Pete_home
      - sensor.Petes_time_to_home
      - sensor.Petes_time_to_home_by_bus
      - sensor.Petes_time_to_home_by_foot
      - sensor.Petes_time_to_home_waze
action:
  - service: notify.logfile
    data:
      message: >
        Location for Pete updated at {{ now() }}
  - service: script.turn_on
    entity_id: script.Pete_travel_sensor
