initial_state: "on"
alias: "Pete home"
trigger:
  - platform: state
    entity_id:
      - device_tracker.3c_28_6d_da_eb_a1
      - device_tracker.Pete_bt_mobile
      - device_tracker.Pete_bt_front_mobile
    to: "home"
  - platform: state
    entity_id: binary_sensor.pi3_front_door_sensor
    to: "off"
  - platform: state
    entity_id: binary_sensor.pi3_front_door_sensor
    to: "on"
  - platform: event
    event_type: automation_reloaded
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: group.person_Pete
    state: "home"
  # Either the door just opened/closed, or multiple trackers show home
  - condition: or
    conditions:
      - condition: numeric_state
        entity_id: group.person_Pete
        above: 1
        value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_Pete', 'entity_id'))|list)|groupby('state'))['home']|count }}"
      - condition: and
        conditions:
          - condition: template
            value_template: >-
              {{ ((now() - states.binary_sensor.pi3_front_door_sensor.last_changed).seconds < 120 ) }}
          - condition: numeric_state
            entity_id: group.person_Pete
            above: 0
            value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_Pete', 'entity_id'))|list)|groupby('state'))['home']|count }}"
action:
  - service: script.turn_on
    entity_id: script.Pete_home
