alias: "Home occupied"
initial_state: true
trigger:
  - platform: state
    entity_id:
      - device_tracker.julie_s20_ping
      - device_tracker.pete_s20_ping
    to: home
#condition:
  #condition: and
  #conditions:
    # We're all away
    #- condition: state
    #  entity_id: input_boolean.julie_is_home
    #  state: "on"
    #- condition: state
    #  entity_id: input_boolean.pete_is_home
    #  state: "on"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.home_occupied