initial_state: true
alias: "Bedtime"
trigger:
  # Everybody is in bed
  - platform: state
    entity_id:
      - input_boolean.julie_in_bed
      - input_boolean.pete_in_bed
    to: on
action:
  - service: notify.logfile
    data:
      message: "Bedtime: {{ states('input_boolean.julie_in_bed') }}/{{ states('input_boolean.Pete_in_bed') }}"
  - service: notify.logfile
    data:
      message: "Bedtime: Everybody is in bed"
  - service: input_boolean.turn_on
    entity_id: input_boolean.bedtime
