alias: 'Guest mode off nobody home'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.guest_mode
    to: 'off'
condition:
  condition: and
  conditions:
    # We're all away
    - condition: state
      entity_id: input_boolean.person3_home
      state: 'off'
    - condition: state
      entity_id: input_boolean.person2_home
      state: 'off'
    - condition: or
      conditions:
      # Either the phone or tablet are away, or the family room isn't occupied
      - condition: state
        entity_id: group.person_person1_tablet
        state: 'not_home'
      - condition: state
        entity_id: input_boolean.person1_home
        state: 'off'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.home_occupied
