alias: "Holiday"
initial_state: "on"
trigger:
  - platform: state
    entity_id:
      - input_boolean.Julie_travelling
      - input_boolean.person3_travelling
      - input_boolean.Pete_travelling
    to: "on"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.Julie_travelling
      state: "on"
    - condition: state
      entity_id: input_boolean.person3_travelling
      state: "on"
    - condition: state
      entity_id: input_boolean.Pete_travelling
      state: "on"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.holiday_mode
