alias: "Holiday over"
initial_state: "on"
trigger:
  - platform: state
    entity_id:
      - input_boolean.Julie_travelling
      - input_boolean.person3_travelling
      - input_boolean.Pete_travelling
    to: "off"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: input_boolean.Julie_travelling
      state: "off"
    - condition: state
      entity_id: input_boolean.person3_travelling
      state: "off"
    - condition: state
      entity_id: input_boolean.Pete_travelling
      state: "off"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.holiday_mode
