alias: Julie Is Home
description: ''
mode: single
trigger:
  - platform: state
    entity_id: device_tracker.julie_s20_ping
    to: home
condition: []
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.julie_is_home