alias: "All away media off"
initial_state: "off"
trigger:
  - platform: state
    entity_id: input_boolean.home_occupied
    to: "off"
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: media_player.office
      state: "playing"
    - condition: state
      entity_id: media_player.family_room
      state: "playing"
    - condition: state
      entity_id: media_player.living_room
      state: "playing"
    - condition: state
      entity_id: media_player.Pete
      state: "playing"
    - condition: state
      entity_id: media_player.Julie
      state: "playing"
action:
  service: media_player.media_pause
