alias: "Julie working away"
initial_state: "on"
trigger:
  - platform: state
    entity_id: calendar.Julie_away
    to: "on"
  - platform: numeric_state
    entity_id: sensor.Julies_time_to_home
    above: "180"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: calendar.Julie_away
      state: "on"
    - condition: numeric_state
      entity_id: sensor.Julies_time_to_home
      above: "180"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.notify_train_status_work
  - service: input_boolean.turn_off
    entity_id: input_boolean.Julie_work_home
  - service: input_boolean.turn_on
    entity_id: input_boolean.Julie_travelling
  - service: input_boolean.turn_on
    entity_id: input_boolean.notify_Julie_working
