initial_state: "on"
alias: "Julie not overseas"
trigger:
  - platform: event
    event_type: tasker_webhook
    event_data:
      who: Julie
condition:
  # Phone is roaming
  - condition: template
    value_template: >-
      {{ trigger.event.data.roaming == "off" }}
  # Not overseas
  - condition: state
    entity_id: input_boolean.Julie_overseas
    state: "on"
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.Julie_overseas
