initial_state: "off"
alias: "Julie GPSLogger tracker"
trigger:
  - platform: template
    value_template: "{{ as_timestamp(states.sensor.date_time.last_updated) - as_timestamp(states.device_tracker.Julie_mobile_gps.last_updated) > 600 }}"
action:
  - service: shell_command.launch_gpslogger_phone
