alias: "Julie working trains"
initial_state: "on"
trigger:
  - platform: state
    entity_id: binary_sensor.workday_sensor
    to: "on"
  - platform: state
    entity_id: input_boolean.notify_Julie_working
    to: "on"
  - platform: state
    entity_id: input_boolean.Julie_travelling
    to: "off"
  - platform: state
    entity_id: input_boolean.Julie_home
    to: "on"
  - platform: state
    entity_id: calendar.Julie_wfh
    to: "off"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
    - condition: state
      entity_id: input_boolean.notify_Julie_working
      state: "on"
    - condition: state
      entity_id: input_boolean.Julie_travelling
      state: "off"
    - condition: state
      entity_id: input_boolean.Julie_home
      state: "on"
    - condition: state
      entity_id: calendar.Julie_wfh
      state: "off"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.notify_train_status_work
  - service: input_boolean.turn_on
    entity_id: input_boolean.notify_Julie_working
