alias: "Julie at gym"
initial_state: "on"
trigger:
  - platform: state
    entity_id: device_tracker.Julie_mobile_gps
    to: "Gym"
    for:
      minutes: 15
action:
  - service: homeassistant.turn_on
    entity_id: automation.Julie_returning_home
  - condition: state
    entity_id: input_boolean.Julie_driving
    state: "on"
  - service: input_boolean.turn_off
    entity_id: input_boolean.Julie_driving
