alias: 'person2 working from home'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: calendar.person2_wfh
    to: 'on'
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: calendar.person2_wfh
    state: 'on'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.notify_train_status_work
  - service: input_boolean.turn_on
    entity_id: input_boolean.person2_work_home
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_travelling
  - service: input_boolean.turn_on
    entity_id: input_boolean.notify_person2_working
