initial_state: "on"
alias: "Julie status update"
trigger:
  # I've moved
  - platform: state
    entity_id:
      - group.person_Julie_work
      - input_boolean.office_occupied
      - input_boolean.Julie_in_bed
      - input_boolean.Julie_is_awake
      - input_boolean.Julie_travelling
      - input_boolean.Julie_overseas
action:
  - service: notify.logfile
    data:
      message: >
        Status for Julie updated at {{ now() }}
  - service: script.turn_on
    entity_id: script.Julie_travel_sensor
