alias: 'person2 not working away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: calendar.person2_away
    to: 'off'
  - platform: numeric_state
    entity_id: sensor.person2s_time_to_home
    below: '180'
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
  - condition: state
    entity_id: calendar.person2_away
    state: 'off'
  - condition: numeric_state
    entity_id: sensor.person2s_time_to_home
    below: '180'
action:
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_travelling
