initial_state: "on"
alias: "Julie overseas"
trigger:
  - platform: event
    event_type: tasker_webhook
    event_data:
      who: Julie
condition:
  # Phone is roaming
  - condition: template
    value_template: >-
      {{ trigger.event.data.roaming == "on" }}
  # Not overseas
  - condition: state
    entity_id: input_boolean.Julie_overseas
    state: "off"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.Julie_overseas
