initial_state: 'on'
alias: 'person2 not driving'
trigger:
  - platform: event
    event_type: tasker_webhook
    event_data:
      who: person2
  - platform: state
    entity_id: sensor.pixel_xl_bluetooth_connection
    attribute: connected_paired_devices
condition: 
  # Leaving, the car
  - condition: or
    conditions:
    - condition: template
      value_template: >-
        {{ '00:0E:9F:7D:6A:96' not in state_attr('sensor.pixel_xl_bluetooth_connection','connected_paired_devices') }}
    - condition: template
      value_template: >-
        {{ trigger.event and ',Exit Car,' in trigger.event.data.what }}
  # Driving
  - condition: state
    entity_id: input_boolean.person2_driving
    state: 'on'
action:
  - service: notify.logfile
    data:
      message: >
        person2 stopped driving at {{ now() }} - waiting to update location
  - service: input_boolean.turn_off
    entity_id: input_boolean.person2_driving
  - wait_for_trigger:
    - platform: state
      entity_id: device_tracker.person2_mobile_gps
  - service: script.turn_on
    entity_id: script.update_car_location
