alias: 'person2 off holiday'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: calendar.person2_holiday
    to: 'off'
  - platform: state
    entity_id: input_boolean.person2_travelling
    to: 'off'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: calendar.person2_holiday
    state: 'off'
  - condition: state
    entity_id: input_boolean.person2_travelling
    state: 'off'
action:
  - service: switch.turn_on
    entity_id: switch.radio_person2
