alias: "Julie not working from home"
initial_state: "on"
trigger:
  - platform: state
    entity_id: calendar.Julie_wfh
    to: "off"
  - platform: state
    entity_id: binary_sensor.workday_sensor
    to: "on"
  - platform: homeassistant
    event: start
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: calendar.Julie_wfh
      state: "off"
    - condition: state
      entity_id: binary_sensor.workday_sensor
      state: "on"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.notify_train_status_work
  - service: input_boolean.turn_off
    entity_id: input_boolean.Julie_work_home
