initial_state: "on"
alias: "Julie in the car"
trigger:
  - platform: event
    event_type: tasker_webhook
    event_data:
      who: Julie
condition:
  # In, or leaving, the car
  - condition: template
    value_template: >-
      {{ 'BT Car' in trigger.event.data.what }}
  # Not home
  - condition: state
    entity_id: input_boolean.Julie_home
    state: "off"
action:
  # Update
  - service: notify.logfile
    data:
      message: >
        Location last updated within last 60 seconds? {{ ( as_timestamp(now()) - as_timestamp(states.device_tracker.Julie_mobile_gps.last_updated)|float)|float < 60 }}
        Location last updated {{ ( as_timestamp(now()) - as_timestamp(states.device_tracker.Julie_mobile_gps.last_updated)|float)|float }} seconds ago
  # Location was updated in the last minute
  - condition: template
    value_template: >-
      {{ ( as_timestamp(now()) - as_timestamp(states.device_tracker.Julie_mobile_gps.last_updated)|float)|float < 60 }}
  - service: script.turn_on
    entity_id: script.Julie_traveltime
  - service: notify.logfile
    data:
      message: >
        Updated travel time because Julie has entered or exited the car, and we received a location update in the last minute
