alias: 'person2 away'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: proximity.person2_home
  - platform: state
    entity_id: 
      - device_tracker.40_4e_36_24_53_15
      - device_tracker.person2_bt_mobile
      - device_tracker.person2_bt_front_mobile
      - device_tracker.person2_wifi
    to: 'not_home'
  - platform: state
    entity_id: input_boolean.person2_driving
    to: 'on'
  - platform: event
    event_type: automation_reloaded
  - platform: homeassistant
    event: start
condition:
  # currently home
  - condition: state
    entity_id: input_boolean.person2_home
    state: 'on'
  - condition: or
    conditions:
    # Driving
    - condition: state
      entity_id: input_boolean.person2_driving
      state: 'on'
    # Two or more trackers mark as away, door opened/closed in the last 5 minutes
    - condition: and
      conditions:
      # More than one tracker shows away
      - condition: template
        value_template: "{{ expand('group.person_person2')|selectattr('state','eq','not_home')|list|count > 1 }}"
        #value_template: "{{ expand('group.person_person2')|selectattr('attributes.source_type','eq','bluetooth')|selectattr('state','eq','home')|list|count }}" # for just Bluetooth trackers
      # An exit door recently opened or closed
      - condition: template
        value_template: "{{ ((now() - states.binary_sensor.pi3_front_door_sensor.last_changed).seconds < 300) or ((now() - states.binary_sensor.pi3_garage_closed_car_sensor.last_changed).seconds < 300) }}"
    # Some away, and not near
    - condition: and
      conditions:
      - condition: template
        value_template: "{{ expand('group.person_person2')|selectattr('state','eq','not_home')|list|count > 0 }}"
      - condition: template
        value_template: "{{ states('proximity.person2_home')|float > 300 }}"
    # Far away
    - condition: template
      value_template: "{{ states('proximity.person2_home')|float > 600 }}"
action:
  - service: script.turn_on
    data:
      entity_id: script.person2_away
