alias: "Workday for Julie too"
initial_state: "on"
trigger:
  - platform: state
    entity_id: input_boolean.Julie_in_bed
    to: "off"
condition:
  condition: and
  conditions:
    - condition: state
      entity_id: calendar.Julie_holiday
      state: "off"
    - condition: state
      entity_id: input_boolean.notify_Julie_working
      state: "off"
    - condition: time
      after: "03:00:00"
      before: "07:00:00"
action:
  - service: input_boolean.turn_on
    entity_id: input_boolean.notify_Julie_working
