initial_state: 'on'
alias: 'person4 home'
trigger:
  - platform: state
    entity_id:
      - device_tracker.00_1d_29_a5_49_ae
      - device_tracker.person4_bt_front_mobile
      - device_tracker.person4_bt_mobile
    to: 'home'
condition:
  - condition: numeric_state
    entity_id: group.person_person4
    above: 0
    value_template: "{{ dict((states|selectattr('entity_id', 'in', state_attr('group.person_person4', 'entity_id'))|list)|groupby('state'))['home']|count }}"
action:
  - service: script.turn_on
    entity_id: script.person4_home
