alias: "HA started"
initial_state: "on"
trigger:
  platform: homeassistant
  event: start
action:
  - service: script.notify_Julie
    data:
      message: "Home Assistant {{ states('sensor.hass_installed') }} has started on Vision ({{ as_timestamp(utcnow())|timestamp_utc }})"
  - service: script.scan_bt_restart
