alias: "HA automations reloaded"
initial_state: true
trigger:
  - platform: event
    event_type: automation_reloaded
action:
  - service: notify.mobile_app_pete_s20
    data:
      message: "Automations on Server have been reloaded at {{ as_timestamp(now())|timestamp_local }} local"
      title: HA automations reloaded
