alias: Ha restart
description: ''
trigger:
- at: 02:00:00
  platform: time
condition:
- condition: time
  weekday:
  - sun
action:
- data: {}
  service: homeassistant.restart
mode: single
