alias: "HA stopped"
initial_state: true
trigger:
  platform: homeassistant
  event: shutdown
action:
  - service: notify.mobile_app_pete_s20
    data:
      message: "Home Assistant {{ states('sensor.hass_installed') }} has shut down on Server ({{ as_timestamp(utcnow())|timestamp_utc }})"
