initial_state: 'on'
alias: 'Zigbee offline long'
trigger:
  - platform: state
    entity_id: sensor.zigbee2mqtt_bridge_state
    to: 'offline'
    for: '00:05:00'
action:
  - service: notify.person2_telegram
    data:
      message: >-
        The Zigbee bridge is offline again
