initial_state: 'on'
alias: 'Zigbee 3 offline'
trigger:
  # No device has update their link in the last half hour
  - platform: template
    value_template: >-
      {{ as_timestamp(now())-as_timestamp(((states|selectattr('attributes.device')|selectattr('attributes.device.zclVersion')|map(attribute='attributes.last_seen'))|list|max)) > 1800 }}
condition:
  - condition: state
    entity_id: sensor.zigbee3_bridge_state
    state: 'online'
action:
  - wait_template: >-
      {{ is_state('input_boolean.person2_home','on') and is_state('input_boolean.person2_is_awake','on') }}
  - service: notify.person2_telegram
    data:
      message: "You need to push the reset button on the ZZH"
